version: '3'
services:
  redis-node-1:
    image: redis
    container_name: redis-node-1
    ports:
      - "7000:6379"
    networks:
      - redis-cluster
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    volumes:
      - redis-node-1-data:/data

  redis-node-2:
    image: redis
    container_name: redis-node-2
    ports:
      - "7001:6379"
    networks:
      - redis-cluster
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    volumes:
      - redis-node-2-data:/data

  redis-node-3:
    image: redis
    container_name: redis-node-3
    ports:
      - "7002:6379"
    networks:
      - redis-cluster
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    volumes:
      - redis-node-3-data:/data

  redis-node-4:
    image: redis
    container_name: redis-node-4
    ports:
      - "7003:6379"
    networks:
      - redis-cluster
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    volumes:
      - redis-node-4-data:/data

  redis-node-5:
    image: redis
    container_name: redis-node-5
    ports:
      - "7004:6379"
    networks:
      - redis-cluster
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    volumes:
      - redis-node-5-data:/data

  redis-node-6:
    image: redis
    container_name: redis-node-6
    ports:
      - "7005:6379"
    networks:
      - redis-cluster
    command: [ "redis-server", "--cluster-enabled", "yes", "--cluster-config-file", "/data/nodes.conf", "--cluster-node-timeout", "5000", "--appendonly", "yes" ]
    volumes:
      - redis-node-6-data:/data

networks:
  redis-cluster:
    driver: bridge

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:
